ALTER TABLE npc CHANGE level original_level DECIMAL(2,0) NULL DEFAULT NULL;
ALTER TABLE npc ADD level DECIMAL(2,0) DEFAULT 85;

ALTER TABLE custom_npc CHANGE level original_level DECIMAL(2,0) NULL DEFAULT NULL;
ALTER TABLE custom_npc ADD level DECIMAL(2,0) DEFAULT 85;
